title: Gem State Cyber
title_separator: "|"
show_downloads: false
remote_theme: "mmistakes/minimal-mistakes@4.20.2"
repository: "U03A9/GemStateCyberSecurity"
minimal_mistakes_skin: "dark" # "default" "air", "aqua", "contrast", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets